int _isupper(char);
int _isdigit(char);
int mul(int, int);
void print_numbers(void);
char _putchar(char);
int print_most_numbers(void);
void more_numbers(void);
void print_line(int);
void print_diagonal(int n);
void print_square(int);
